// https://docs.expo.dev/guides/using-eslint/
const { defineConfig } = require("eslint/config");
const expoConfig = require("eslint-config-expo/flat");

module.exports = defineConfig([
  expoConfig,
  {
    // `src/generated` is fluorite's output, regenerated by `npm run
    // generate-types`. Linting it reports on the generator's choices, which
    // nobody here can act on — an empty `.fl` struct is an empty interface,
    // and that is correct.
    ignores: ["dist/*", "src/generated/*"],
  },
]);
