const js = require("@eslint/js");
const tseslint = require("typescript-eslint");
const reactHooks = require("eslint-plugin-react-hooks");

// Deliberately not `@react-native/eslint-config`: it is eslintrc-shaped, needs
// a compat layer, and pulls Flow plugins for a codebase with no Flow in it.
// What earns its place is the hooks plugin — a conditional hook is invisible
// to `tsc` and fatal at runtime, and this migration introduced six of them.
module.exports = [
  {
    ignores: [
      "node_modules/**",
      "ios/**",
      "android/**",
      // fluorite's output, regenerated by `npm run generate-types`. Linting it
      // reports on the generator's choices, which nobody here can act on.
      "src/generated/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ["**/*.{ts,tsx}"],
    plugins: { "react-hooks": reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
  {
    // The build config and the entry point are CommonJS running under Node.
    files: ["*.config.js", "index.js"],
    languageOptions: { sourceType: "commonjs", globals: { module: "writable", require: "readonly", __dirname: "readonly" } },
    rules: { "@typescript-eslint/no-require-imports": "off" },
  },
  {
    files: ["src/**/*.test.ts"],
    languageOptions: { globals: { __dirname: "readonly" } },
  },
];
